"""add user_id to request_logs

Revision ID: 55a5953a5df9
Revises: fc740e38b96f
Create Date: 2026-08-24 20:37:04.663381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a5953a5df9'
down_revision: Union[str, Sequence[str], None] = 'fc740e38b96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('request_logs', 'api_key_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'request_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_logs', type_='foreignkey')
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.alter_column('request_logs', 'api_key_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('request_logs', 'user_id')
    # ### end Alembic commands ###
